SELECT DECK.ID AS DECKID, DECK.OMSCHRIJVING, CARD.ID AS CARDID, CARD.NAAM, CARD.AFBEELDING
FROM DECKCARD
LEFT JOIN CARD ON CARD.ID = DECKCARD.CARDID
LEFT JOIN DECK ON DECK.ID = DECKCARD.DECKID
WHERE DECK.PLAYERID = :playerid
ORDER BY DECK.ID;