set serveroutput on;

/*
DROP TABLEs
*/
DROP TABLE SPELER cascade constraints;
DROP TABLE UITVINDING cascade constraints;
DROP TABLE SPELER_RECEPT cascade constraints;
DROP TABLE INGREDIENTVOORRAAD cascade constraints;
DROP TABLE RECEPT cascade constraints;
DROP TABLE RECEPTRESULTATEN cascade constraints;
DROP TABLE VOORWERP cascade constraints;
DROP TABLE INGREDIENT cascade constraints;
DROP TABLE RECEPT_INGREDIENT cascade constraints;
DROP TABLE WINKELAANBOD cascade constraints;
DROP TABLE WINKEL cascade constraints;

/*
CREATE TABLEs
Inclusief PKs, single-column CHECKs en single-column UNIQUEs
*/
CREATE TABLE SPELER(
	ID				NUMBER(8)		PRIMARY KEY,
	naam			VARCHAR2(255)	NOT NULL,
	e-mail			VARCHAR2(255)	NOT NULL,
	geld			NUMBER(15)		NOT NULL,
);

CREATE TABLE VOORWERP(
	ID				NUMBER(8)		PRIMARY KEY,
	naam			VARCHAR2(255)	NOT NULL,
	waarde			NUMBER(8)		NOT NULL
);

CREATE TABLE UITVINDING(
	IDspeler		NUMBER(8)		REFERENCES SPELER(ID),
	IDvoorwerp		NUMBER(8)		REFERENCES VOORWERP(ID),
	aantal			NUMBER(15)		NULL
	
	CONSTRAINT PK_UITVINDING PRIMARY KEY(IDspeler, IDvoorwerp)
);

CREATE TABLE INGREDIENT(
	ID				NUMBER(8)		PRIMARY KEY,
	naam			NUMBER(8)		NOT NULL,
	prijs			NUMBER(8)		NOT NULL
);

CREATE TABLE RECEPT(
	ID				NUMBER(8) 		PRIMARY KEY,
	IDingredient	NUMBER(8) 		REFERENCES INGREDIENT(ID),
	IDvoorwerp		NUMBER(8)		REFERENCES VOORWERP(ID)
);

CREATE TABLE SPELER_RECEPT(
	IDspeler 		NUMBER(8)		REFERENCES SPELER(ID),
	IDrecept		NUMBER(8)		REFERENCES RECEPT(ID),
	
	CONSTRAINT PK_SPELER_RECEPT PRIMARY KEY(IDspeler, IDrecept)
);

CREATE TABLE INGREDIENTVOORRAAD(
	IDspeler		NUMBER(8)		REFERENCES SPELER(ID),
	IDingredient	NUMBER(8)		REFERENCES INGREDIENT(ID),
	aantal			NUMBER(8),
	
	CONSTANT PK_INGREDIENTVOORRAAD 	PRIMARY KEY (IDspeler, IDingredient)
);

CREATE TABLE RECEPTRESULTATEN(
	ID				NUMBER(8)		PRIMARY KEY,
	IDrecept		NUMBER(8)		REFERENCES RECEPT(ID),
	IDingredient	NUMBER(8)		REFERENCES INGREDIENT(ID),
	IDvoorwerp		NUMBER(8)		REFERENCES VOORWERP(ID)
);

CREATE TABLE RECEPT_INGREDIENT(
	IDrecept		NUMBER(8)		REFERENCES RECEPT(ID),
	IDingredient	NUMBER(8)		REFERENCES INGREDIENT(ID),
	
	CONSTRAINT PK_RECEPT_INGREDIENT	PRIMARY KEY(IDrecept, IDingredient)
);

CREATE TABLE WINKEL(
	ID				NUMBER(8)		PRIMARY KEY,
	naam			NUMBER(8)		NOT NULL,
	adres			NUMBER(8)		NOT NULL
);

CREATE TABLE WINKELAANBOD(
	IDwinkel		NUMBER(8)		REFERENCES WINKEL(ID),
	IDingredient	NUMBER(8)		REFERENCES INGREDIENT(ID),
	prijs			NUMBER(8)		NOT NULL,
	
	CONSTRAINT PK_WINKELAANBOD 		PRIMARY KEY(IDwinkel, IDingredient)
);